version: "3.6"

services:
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017
    tmpfs:
      - /data/db

  api:
    environment:
      - NODE_ENV=test
      - PORT=8080
      - GITHUB_API_URL=https://api.github.com
      - MONGO_URL=mongodb://mongodb
    ports:
      - 8080:8080
    command: sh -c "npm run build && npm start"
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    environment:
      - PORT=80
      - REACT_APP_API_URL=http://api:8080
    ports:
      - 80:80
    command: sh -c "npm start"